language: php

php:
    - 5.5
    - 5.6

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev

script:
	- vendor/bin/phpcs --standard=PSR1 src/
	- vendor/bin/phpcs --standard=PSR2 src/
	- vendor/bin/phpunit -c phpunit.xml.dist